#name: Build and push container image

#on:
  #push:
 #   tags:
#      - '*'

#env:
#  IMAGE_NAME: vegardg/bakemyday
#jobs:
  #build-and-push:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout code
       # uses: actions/checkout@v3

      #- name: Set up Docker Buildx
       # uses: docker/setup-buildx-action@v1

      #- name: Login to Docker
        #uses: docker/login-action@v1
        #with:
        #  username: ${{ secrets.DOCKERHUB_USERNAME }}
       #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and push Docker image
        #uses: docker/build-push-action@v2
        #with:
          #context: .
          #push: true
          #tags: ${{ env.IMAGE_NAME }}:${{ github.ref }}
name: Build and Push Container Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: vegardg/bakemyday

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract tag name
        run: echo "::set-output name=TAG_NAME::${{ github.ref/refs\/tags\// }}"
        id: extract_tag_name
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.extract_tag_name.outputs.TAG_NAME }}
