
name: Build and Push Container Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: vegardg/bakemyday

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract tag name
        id: tagname
        run: echo "::set-output name=tagname::$(echo ${GITHUB_REF#refs/tags/})"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.tagname.outputs.tagname }}
